output_dir: 'output/lincls/vit_small_patch16_224_GAP'

# Architecture
model: vit_small_patch16_224
use_cls_token: False # not use cls-token

# Train
epochs: 90
opt: sgd
lr: 0.1
weight_decay: 0.0
warmup_epochs: 10
batch_size: 512
dist_eval: True

# Data Aug
mixup: 0.0
cutmix: 0.0
#reprob: 0.25

# Wandb
log_wandb: True
wandb_project: 'MAE-Linear_Probe'