output_dir: 'output/finetune/vit_large_patch16_224_GAP'

# Architecture
model: vit_large_patch16_224
use_mean_pooling: True # not use cls-token
drop_path: 0.1

# Train
epochs: 50
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 128
dist_eval: True
#reprob: 0.25

# Wandb
log_wandb: True
wandb_project: 'MAE-Finetune'