output_dir: 'output/finetune/vit_base_patch16_224_GAP_pretrain400'

# Architecture
model: vit_base_patch16_224
use_cls_token: False # not use cls-token
drop_path: 0.1

# Train
epochs: 100
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 128
dist_eval: True
#reprob: 0.25

# Wandb
wandb_project: 'MAE-Finetune'