output_dir: 'output/finetune/vit_small_patch16_224_GAP'

# Architecture
model: vit_small_patch16_224
use_cls_token: False # not use cls-token

# Train
epochs: 50
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 128
dist_eval: True
#reprob: 0.25

# Wandb
wandb_project: 'MAE-Finetune'