output_dir: 'output/finetune/prit_small_LGGG_224_GAP_dilated'

# Architecture
model: prit_local_small_LGGG_224
use_mean_pooling: True # not use cls-token
blocks: [[dilated, local], normal, normal, normal]

# Train
epochs: 50
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 32
update_freq: 4
dist_eval: True
#reprob: 0.25

# Wandb
log_wandb: True
wandb_project: 'PriT_Finetune'