output_dir: 'output/finetune/prit_small_LGGG_224_GAP_100E'

# Architecture
model: prit_local_small_LGGG_224
use_mean_pooling: True # not use cls-token

# Train
epochs: 100
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 32
update_freq: 4
dist_eval: True
#reprob: 0.25

# Wandb
log_wandb: True
wandb_project: 'PriT_Finetune'