output_dir: 'output/finetune/prit_small_patch16_224_GAP'

# Architecture
model: vit_small_patch16_224
use_mean_pooling: True # not use cls-token

# Train
epochs: 50
opt: adamw
weight_decay: 0.05
warmup_epochs: 10
batch_size: 4
update_freq: 32
dist_eval: True
#reprob: 0.25

# Wandb
log_wandb: True
wandb_project: 'PriT-Finetune'